server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/lms_auth_db
    username: postgres
    password: root   # <-- CHANGE TO YOUR LOCAL POSTGRES PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # In production, validate ensures the entity mapping matches Flyway schema exactly
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info