server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # Do not register Eureka with itself
    register-with-eureka: false
    # Do not fetch registry from other servers (we are running standalone in dev)
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/